# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetracker',
            name='data_file_kind',
            field=models.CharField(choices=[('NCVHis', 'NCVHis file'), ('NCVoter', 'NCVoter file')], default='NCVHis', max_length=7, verbose_name='Data file kind'),
            preserve_default=False,
        ),
    ]
