# Generated by Django 2.0.2 on 2018-02-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetracker',
            name='change_tracker_processed',
            field=models.BooleanField(default=False),
        ),
    ]
