# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_filetracker_data_file_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvoter',
            name='age',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ncvoter',
            name='registr_dt',
            field=models.DateTimeField(verbose_name='registr_dt'),
        ),
    ]
