# Generated by Django 2.0.2 on 2018-03-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0002_filetracker_change_tracker_processed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ncvoter',
            table=None,
        ),
    ]
