# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0003_auto_20170430_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='voted_county_id',
            field=models.SmallIntegerField(blank=True, max_length=3, verbose_name='voted_county_id'),
        ),
    ]
