# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20170430_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='voted_county_id',
            field=models.SmallIntegerField(verbose_name='voted_county_id'),
        ),
    ]
