# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20170530_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='voting_method',
            field=models.CharField(blank=True, max_length=32, verbose_name='voting_method'),
        ),
    ]
