# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20170430_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetracker',
            name='model_name',
            field=models.CharField(choices=[('NCVHis', 'NCVHis file'), ('NCVoter', 'NCVoter file')], max_length=20, verbose_name='Model Name'),
        ),
    ]
