# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20170530_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetracker',
            name='op_code',
            field=models.CharField(choices=[('A', 'Add'), ('M', 'Modify')], max_length=1, verbose_name='Operation Code'),
        ),
    ]
