# Generated by Django 2.0.2 on 2018-03-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_ncvoter_registr_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncvoter',
            name='data',
        ),
        migrations.RemoveField(
            model_name='ncvoter',
            name='registr_dt',
        ),
    ]
