# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_auto_20170430_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='voter.NCVoter', to_field='ncid'),
        ),
    ]
