# Generated by Django 2.0.2 on 2018-03-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_auto_20180309_1659'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='changetracker',
            unique_together={('ncid', 'snapshot_dt')},
        ),
    ]
