# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_auto_20170512_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='voting_method',
            field=models.CharField(blank=True, max_length=16, verbose_name='voting_method'),
        ),
    ]
