# Generated by Django 2.0.2 on 2018-03-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0007_auto_20180309_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetracker',
            name='voter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='voter.NCVoter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='changetracker',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='changetracker',
            name='ncid',
        ),
    ]
