# Generated by Django 2.0.2 on 2018-03-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0008_auto_20180309_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetracker',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='voter.NCVoter'),
        ),
    ]
