# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0008_auto_20170512_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvhis',
            name='election_lbl',
            field=models.DateField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ncvoter',
            name='registr_dt',
            field=models.DateField(verbose_name='registr_dt'),
        ),
    ]
