# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_auto_20170512_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetracker',
            name='election_desc',
            field=models.CharField(blank=True, max_length=230, verbose_name='election_desc'),
        ),
    ]
