# Generated by Django 2.0.2 on 2018-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0009_auto_20180309_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changetracker',
            options={'ordering': ('snapshot_dt',), 'verbose_name': 'Change Tracker', 'verbose_name_plural': 'Change Tracking'},
        ),
        migrations.AddField(
            model_name='changetracker',
            name='file_lineno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
