# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0010_changetracker_election_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='changetracker',
            name='md5_hash',
            field=models.CharField(default='', max_length=32, verbose_name='MD5 Hash Value'),
            preserve_default=False,
        ),
    ]
