# Generated by Django 2.0.2 on 2018-03-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0011_badline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badline',
            unique_together={('filename', 'line_no')},
        ),
    ]
