# Generated by Django 2.0.2 on 2018-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0012_auto_20180314_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badline',
            name='message',
            field=models.TextField(db_index=True),
        ),
    ]
