# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0012_auto_20170513_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncvoter',
            name='middle_name',
            field=models.CharField(default='', max_length=25, verbose_name='middle_name'),
            preserve_default=False,
        ),
    ]
