# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0013_ncvoter_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncvoter',
            name='confidential_ind',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
