# Generated by Django 2.0.2 on 2018-03-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_auto_20180319_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changetracker',
            options={'ordering': ('snapshot_dt', 'op_code'), 'verbose_name': 'Change Tracker', 'verbose_name_plural': 'Change Tracking'},
        ),
    ]
