# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0014_ncvoter_confidential_ind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncvoter',
            name='Confidential_ind',
        ),
    ]
