# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_remove_ncvoter_confidential_ind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncvhis',
            name='md5_hash',
        ),
        migrations.RemoveField(
            model_name='ncvoter',
            name='md5_hash',
        ),
    ]
