# Generated by Django 2.0.2 on 2018-04-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_auto_20180328_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadLineRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('first_line_no', models.IntegerField()),
                ('last_line_no', models.IntegerField()),
                ('example_line', models.TextField(help_text='First line from this range')),
                ('message', models.TextField(db_index=True)),
                ('is_warning', models.BooleanField()),
            ],
        ),
    ]
