# Generated by Django 2.0.2 on 2018-03-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_auto_20180321_2018'),
    ]

    operations = [
        migrations.RunSQL(
            "create index change_data on voter_changetracker(data) where op_code = 'M'",
            "drop index change_data",
        ),
    ]
