# Generated by Django 2.0.2 on 2018-04-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0015_auto_20180328_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetracker',
            name='change_tracker_processed',
        ),
    ]
