# Generated by Django 2.0.2 on 2018-04-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0018_convert_badlines'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BadLine',
        ),
        migrations.AlterUniqueTogether(
            name='badlinerange',
            unique_together={('filename', 'first_line_no')},
        ),
    ]
