# Generated by Django 2.0.4 on 2018-04-12 15:42

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0019_auto_20180404_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncvoter',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Most recently known registration data for this voter.'),
        ),
        migrations.AddField(
            model_name='ncvoter',
            name='deleted',
            field=models.BooleanField(default=False, help_text='True if this voter not seen in most recent registration data.'),
        ),
        migrations.AlterField(
            model_name='changetracker',
            name='op_code',
            field=models.CharField(choices=[('A', 'Add'), ('M', 'Modify'), ('N', 'No change')], max_length=1, verbose_name='Operation Code'),
        ),
    ]
