# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0019_auto_20170514_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncvoter',
            name='birth_age',
            field=models.IntegerField(),
        ),
    ]
