# Generated by Django 2.0.4 on 2018-04-16 12:00

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0021_set_current_voter_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changetracker',
            name='op_code',
            field=models.CharField(choices=[('A', 'Add'), ('M', 'Modify')], max_length=1, verbose_name='Operation Code'),
        ),
        migrations.AlterField(
            model_name='ncvoter',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Most recently known registration data for this voter, or NULL.', null=True),
        ),
    ]
