# Generated by Django 2.0.4 on 2018-04-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0021_index_data'),
        ('voter', '0019_auto_20180404_1750'),
    ]

    operations = [
    ]
