# Generated by Django 2.0.4 on 2018-04-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0024_change_data_index'),
    ]

    operations = [
        migrations.RunSQL(
            "create index change_voter_idx on voter_changetracker(voter_id, snapshot_dt)",
            "drop index change_voter_idx",
        ),
    ]
