# Generated by Django 2.0.4 on 2018-04-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0025_change_voter_index'),
        ('voter', '0022_auto_20180416_1200'),
    ]

    operations = [
    ]
