# Generated by Django 2.0.4 on 2018-05-31 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0027_auto_20180417_1418'),
    ]

    operations = [
        migrations.RunSQL(
            "create index voter_ncvoter_data_index on voter_ncvoter using GIN(data)",
            "drop index voter_ncvoter_data_index",
        ),
    ]
