# Generated by Django 2.0.4 on 2018-06-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0029_make_age_numeric'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCVoterQueryView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_cd', models.CharField(max_length=3, verbose_name='party code')),
                ('county_id', models.IntegerField(verbose_name='county code')),
                ('race_code', models.CharField(max_length=1, verbose_name='race code')),
                ('ethnic_code', models.CharField(max_length=2, verbose_name='ethnicity code')),
                ('status_cd', models.CharField(max_length=1, verbose_name='voter status code')),
                ('birth_state', models.CharField(blank=True, max_length=2, verbose_name='birth state')),
                ('gender_code', models.CharField(max_length=1, verbose_name='gender code')),
                ('age', models.IntegerField(null=True)),
                ('res_city_desc', models.CharField(blank=True, max_length=30, verbose_name='city of residence')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='zip code')),
            ],
            options={
                'db_table': 'voter_ncvoterqueryview',
                'managed': False,
            },
        ),
        migrations.RunSQL(
            """
            CREATE MATERIALIZED VIEW voter_ncvoterqueryview AS
            SELECT id,
                   data->>'party_cd' AS party_cd,
                   (data->>'county_id')::integer AS county_id,
                   data->>'race_code' AS race_code,
                   data->>'ethnic_code' AS ethnic_code,
                   data->>'status_cd' AS status_cd,
                   coalesce(data->>'birth_state', data->>'birth_place') AS birth_state,
                   coalesce(data->>'gender_code', data->>'sex_code') AS gender_code,
                   coalesce(data->>'birth_age', data->>'age')::integer AS age,
                   data->>'res_city_desc' AS res_city_desc,
                   data->>'zip_code' AS zip_code
             FROM voter_ncvoter;

            CREATE UNIQUE INDEX ON voter_ncvoterqueryview(id);
            CREATE INDEX ON voter_ncvoterqueryview(party_cd);
            CREATE INDEX ON voter_ncvoterqueryview(race_code);
            CREATE INDEX ON voter_ncvoterqueryview(ethnic_code);
            CREATE INDEX ON voter_ncvoterqueryview(status_cd);
            CREATE INDEX ON voter_ncvoterqueryview(gender_code);
            CREATE INDEX ON voter_ncvoterqueryview(age);
            CREATE INDEX ON voter_ncvoterqueryview(res_city_desc);
            CREATE INDEX ON voter_ncvoterqueryview(zip_code);
            """,
            """
            DROP MATERIALIZED VIEW voter_ncvoterqueryview;
            """
        )
    ]
