# Generated by Django 2.0.4 on 2018-06-11 14:38

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0030_ncvoterqueryview'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCVoterQueryCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qs_filters', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Dictionary of queryset filters for NCVoterQueryView.', unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
