# Generated by Django 2.0.6 on 2018-06-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0031_ncvoterquerycache'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP MATERIALIZED VIEW IF EXISTS voter_ncvoterqueryview;
            CREATE MATERIALIZED VIEW voter_ncvoterqueryview AS
            SELECT id,
                   data->>'party_cd' AS party_cd,
                   (data->>'county_id')::integer AS county_id,
                   CASE WHEN data->>'ethnic_code' = 'HL'
                     THEN 'H'
                     ELSE data->>'race_code'
                   END AS race_ethnicity_code,
                   data->>'status_cd' AS status_cd,
                   coalesce(data->>'birth_state', data->>'birth_place') AS birth_state,
                   coalesce(data->>'gender_code', data->>'sex_code') AS gender_code,
                   coalesce(data->>'birth_age', data->>'age')::integer AS age,
                   data->>'res_city_desc' AS res_city_desc,
                   data->>'zip_code' AS zip_code
             FROM voter_ncvoter;

            CREATE UNIQUE INDEX ON voter_ncvoterqueryview(id);
            CREATE INDEX ON voter_ncvoterqueryview(party_cd);
            CREATE INDEX ON voter_ncvoterqueryview(race_ethnicity_code);
            CREATE INDEX ON voter_ncvoterqueryview(status_cd);
            CREATE INDEX ON voter_ncvoterqueryview(gender_code);
            CREATE INDEX ON voter_ncvoterqueryview(age);
            CREATE INDEX ON voter_ncvoterqueryview(res_city_desc);
            CREATE INDEX ON voter_ncvoterqueryview(zip_code);
            """,
            """
            DROP MATERIALIZED VIEW voter_ncvoterqueryview;
            """
        )
    ]
