# Generated by Django 2.0.4 on 2018-05-17 20:23
import itertools

from django.db import migrations
from matview.dbutils import make_matview_migration


class Migration(migrations.Migration):

    dependencies = [
        ('queryviews', '0002_party'),
    ]

    operations = itertools.chain(*(
        make_matview_migration("voter.NCVoter", {"party_cd": "REP"}, {"sex_code": "F"}),
        make_matview_migration("voter.NCVoter", {"party_cd": "REP"}, {"sex_code": "M"}),
        make_matview_migration("voter.NCVoter", {"party_cd": "DEM"}, {"sex_code": "F"}),
        make_matview_migration("voter.NCVoter", {"party_cd": "DEM"}, {"sex_code": "M"}),
    ))
