# Generated by Django 2.0.4 on 2018-05-22 20:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('queryviews', '0003_combo_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_dem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_dem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_dem_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_dem__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_rep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_rep_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_f_xx_party_cd_rep__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_dem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_dem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_dem_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_dem__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_rep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_rep_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_gender_code_m_xx_party_cd_rep__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_party_cd_dem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_party_cd_dem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_party_cd_dem_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_party_cd_dem__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_party_cd_rep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_party_cd_rep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_party_cd_rep_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_party_cd_rep__count',
                'managed': False,
            },
        ),
    ]
