# Generated by Django 2.0.4 on 2018-06-04 17:21
import itertools

from django.db import migrations

from matview.dbutils import make_matview_migration
from drilldown.filters import RaceFilter


class Migration(migrations.Migration):

    dependencies = [
        ('queryviews', '0007_race_flags'),
    ]

    operations = itertools.chain(*(
        make_matview_migration("voter.NCVoter", None, {raceflag: "true"})
        for raceflag in RaceFilter.get_raceflags(2)
    ))
