# Generated by Django 2.0.4 on 2018-06-05 13:16

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryviews', '0007_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_active',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_active',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_active_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_active__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_denied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_denied',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_denied_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_denied__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_inactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_inactive',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_inactive_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_inactive__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_removed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_removed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_removed_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_removed__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_temporary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_voter_status_desc_temporary_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_voter_status_desc_temporary__count',
                'managed': False,
            },
        ),
    ]
