# Generated by Django 2.0.4 on 2018-06-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryviews', '0008_matview_mv_voter_ncvoter_voter_status_desc_active_matview_mv_voter_ncvoter_voter_status_desc_active_'),
        ('queryviews', '0008_race_flag_matviews'),
    ]

    operations = [
    ]
