# Generated by Django 2.0.4 on 2018-06-05 20:34

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryviews', '0009_merge_20180605_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_a_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_a_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_a_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_a_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ab_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ab_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ab_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ab_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ai_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ai_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ai_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ai_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_am_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_am_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_am_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_am_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ao_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ao_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ao_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ao_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_au_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_au_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_au_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_au_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_aw_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_aw_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_aw_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_aw_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_b_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_b_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_b_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_b_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bi_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bi_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bi_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bi_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bm_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bm_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bm_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bm_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bo_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bo_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bo_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bo_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bu_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bu_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bu_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bu_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bw_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bw_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_bw_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_bw_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_i_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_i_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_i_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_i_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_im_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_im_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_im_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_im_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_io_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_io_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_io_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_io_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_iu_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_iu_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_iu_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_iu_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_iw_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_iw_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_iw_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_iw_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_m_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_m_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_m_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_m_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mo_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mo_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mo_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mo_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mu_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mu_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mu_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mu_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mw_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mw_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_mw_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_mw_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_o_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_o_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_o_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_o_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ou_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ou_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ou_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ou_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ow_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ow_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_ow_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_ow_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_u_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_u_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_u_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_u_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_uw_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_uw_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_uw_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_uw_true__count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_w_true',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncid', models.CharField(max_length=12, verbose_name='ncid')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_w_true',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matview_mv_voter_ncvoter_raceflag_w_true_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'matview_mv_voter_ncvoter_raceflag_w_true__count',
                'managed': False,
            },
        ),
    ]
