---
- hosts: worker
  become: yes
  tasks:
  - name: Regularly update voter data via cron
    cron:
      cron_file: voter-process
      hour: 2
      minute: 0
      user: "{{ project_name }}"
      job: cd /var/www/{{ project_name }}; ./manage.sh voter_fetch; ./manage.sh voter_process_snapshot
