---
- hosts: worker
  become: yes
  tasks:
  - name: Regularly update voter data via cron
    cron:
      name: Fetch and Process Voter Data
      cron_file: voter-process
      hour: 2
      minute: 0
      user: "{{ project_name }}"
      # send output to syslog: https://serverfault.com/a/434902/218035
      job: cd /var/www/{{ project_name }}; ./manage.sh voter_fetch 2>&1 | /usr/bin/logger -t voter_fetch; ./manage.sh voter_process_snapshot 2>&1 | /usr/bin/logger -t voter_process; ./manage.sh refresh_matviews 2>&1 | /usr/bin/logger -t refresh_matviews
    when: env_name != 'staging'
