# Generated by Django 2.0.4 on 2018-05-18 12:16

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voter', '0027_auto_20180417_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('table_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matview.MatView', blank=True, null=True)),
            ],
        ),
    ]
