# Generated by Django 2.0.4 on 2018-05-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='matview.MatView'),
        ),
    ]
