# Generated by Django 2.0.4 on 2018-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matview', '0002_auto_20180522_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matview',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
