# Generated by Django 2.0.4 on 2018-06-11 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matview', '0003_auto_20180531_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matview',
            name='parent',
        ),
        migrations.DeleteModel(
            name='MatView',
        ),
    ]
